import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { deriveLiveFeatures, type GoalHistoryPoint } from "../model/liveFeatureAdapter.ts";
import { explainInference, NEXT_GOAL_NONE_MODEL } from "../model/nextGoalNoneModel.ts";
import { AUTHORED_DEMO_FIXTURE } from "./authoredDemoScenario.ts";
import type { Match } from "../types.ts";

// ---------------------------------------------------------------------------
// Tests for the expanded bundled StatsBomb fixture set under
// lib/historical/bundled/ (see ml/build_bundled_replay_fixture.py) and its
// static manifest (lib/historical/bundled/manifest.ts, generated by
// scripts/generate-bundled-fixture-manifest.ts). lib/historical/provider.ts
// and lib/historical/bundledProvider.ts both start with `import
// "server-only"`, which only Next.js's bundler tolerates -- run directly via
// node --test it throws unconditionally (see scripts/audit-hero-fixture.ts's
// identical note). So, like every other wiring test in this repo, this file
// either (a) reads raw fixture JSON directly with node:fs, mirroring
// ml/audit_bundled_fixtures.py's own checks as executable tests, or (b)
// source-scans provider.ts/bundledProvider.ts's actual text to prove their
// resolution-order logic structurally, rather than importing them.
// ---------------------------------------------------------------------------

const ROOT = process.cwd();
const BUNDLED_DIR = path.join(ROOT, "lib", "historical", "bundled");
const MINUTE_EPSILON = 0.01;

interface GoalPoint {
  minute: number;
  homeScore: number;
  awayScore: number;
}

interface Snapshot {
  label: string;
  minute: number;
  homeScore: number;
  awayScore: number;
  redCardsHome: number;
  redCardsAway: number;
  goalHistory: GoalPoint[];
}

interface BundledFixtureJson {
  source: string;
  sourceAttribution: string;
  fixtureId: string;
  homeParticipantId: number;
  awayParticipantId: number;
  homeName: string;
  awayName: string;
  finalHomeScore: number;
  finalAwayScore: number;
  finalMinute: number;
  latestNextGoalNoneOdds: number | null;
  state: { goalHistory: GoalPoint[]; redCardsHome: number; redCardsAway: number };
  snapshots: Snapshot[];
}

async function loadBundledFixtures(): Promise<{ fileName: string; raw: string; fixture: BundledFixtureJson }[]> {
  const fileNames = (await readdir(BUNDLED_DIR)).filter((f) => f.endsWith(".json")).sort((a, b) => a.localeCompare(b));
  return Promise.all(
    fileNames.map(async (fileName) => {
      const raw = await readFile(path.join(BUNDLED_DIR, fileName), "utf-8");
      return { fileName, raw, fixture: JSON.parse(raw) as BundledFixtureJson };
    }),
  );
}

async function readSource(relativePath: string): Promise<string> {
  return readFile(path.join(ROOT, relativePath), "utf-8");
}

const PLACEHOLDER_STRENGTH = 75; // matches provider.ts/HistoricalAnalysis.tsx's own placeholder convention

function buildMatch(f: BundledFixtureJson, snap: Snapshot): Match {
  return {
    id: `test-${f.fixtureId}-${snap.minute}`,
    home: { id: String(f.homeParticipantId), name: f.homeName, shortName: "HOM", strength: PLACEHOLDER_STRENGTH },
    away: { id: String(f.awayParticipantId), name: f.awayName, shortName: "AWY", strength: PLACEHOLDER_STRENGTH },
    homeScore: snap.homeScore,
    awayScore: snap.awayScore,
    minute: snap.minute,
    status: snap.label === "Full time" ? "finished" : "live",
    stats: {
      possession: [50, 50],
      shots: [0, 0],
      shotsOnTarget: [0, 0],
      corners: [0, 0],
      attackingPressure: [50, 50],
      redCards: [snap.redCardsHome, snap.redCardsAway],
    },
    marketMovement: 0,
    totalGoalsLine: 2.5,
  };
}

// --- 1. at least 10 bundled/deployed replay fixtures are available ---------

test("at least 10 replay fixtures are available with zero local TxLINE data on disk (bundled StatsBomb fixtures + the always-present authored demo scenario)", async () => {
  const bundled = await loadBundledFixtures();
  // provider.ts's listHistoricalFixtures() always appends exactly one more
  // -- the hand-authored demo scenario (see authoredDemoScenario.ts) -- on
  // top of whichever of real TxLINE / bundled StatsBomb is in use.
  const totalWithNoLocalTxline = bundled.length + 1;
  assert.ok(
    totalWithNoLocalTxline >= 10,
    `expected at least 10 deployed replay fixtures (bundled + authored demo) with no local TxLINE data, got ${totalWithNoLocalTxline}`,
  );
  assert.ok(bundled.length >= 9, `expected at least 9 bundled StatsBomb fixtures, got ${bundled.length}`);
});

// --- 2. all bundled fixture IDs are unique ----------------------------------

test("every bundled fixture has a unique fixtureId, and none collide with the authored demo scenario's fixtureId", async () => {
  const bundled = await loadBundledFixtures();
  const ids = bundled.map((b) => b.fixture.fixtureId);
  assert.equal(new Set(ids).size, ids.length, "duplicate fixtureId found among bundled fixtures");
  assert.ok(!ids.includes(AUTHORED_DEMO_FIXTURE.fixtureId), "a bundled fixtureId must never collide with the authored demo scenario's fixtureId");
});

// --- 3. all fixtures have valid source attribution --------------------------

test("every bundled fixture carries non-empty StatsBomb source attribution, and is never labelled txline_downloaded or authored_demo_scenario", async () => {
  const bundled = await loadBundledFixtures();
  for (const { fileName, fixture } of bundled) {
    assert.equal(fixture.source, "statsbomb_open_data_bundled", `${fileName}: unexpected source`);
    assert.ok(fixture.sourceAttribution && fixture.sourceAttribution.trim().length > 0, `${fileName}: missing sourceAttribution`);
    assert.ok(fixture.sourceAttribution.includes("StatsBomb"), `${fileName}: sourceAttribution must credit StatsBomb`);
  }
});

// --- 4. scores agree with the goal timeline ---------------------------------

test("every bundled fixture's declared final score agrees with its own goal-history timeline, and no goal occurs after the declared match duration", async () => {
  const bundled = await loadBundledFixtures();
  for (const { fileName, fixture } of bundled) {
    const goals = fixture.state.goalHistory;
    const last = goals[goals.length - 1];
    assert.ok(last, `${fileName}: empty goal history`);
    assert.equal(last.homeScore, fixture.finalHomeScore, `${fileName}: final home score mismatch`);
    assert.equal(last.awayScore, fixture.finalAwayScore, `${fileName}: final away score mismatch`);
    for (const g of goals) {
      assert.ok(g.minute <= fixture.finalMinute + MINUTE_EPSILON, `${fileName}: goal at ${g.minute}' occurs after declared duration ${fixture.finalMinute}'`);
    }
  }
});

// --- 5. replay snapshots contain no future-event leakage --------------------

test("no bundled fixture snapshot's goalHistory contains a goal after that snapshot's own minute", async () => {
  const bundled = await loadBundledFixtures();
  for (const { fileName, fixture } of bundled) {
    for (const snap of fixture.snapshots) {
      for (const g of snap.goalHistory) {
        assert.ok(
          g.minute <= snap.minute + MINUTE_EPSILON,
          `${fileName}: snapshot "${snap.label}" (${snap.minute}') leaks a future goal at ${g.minute}'`,
        );
      }
      const expected = fixture.state.goalHistory.filter((g) => g.minute <= snap.minute + MINUTE_EPSILON);
      assert.equal(
        snap.goalHistory.length,
        expected.length,
        `${fileName}: snapshot "${snap.label}" goalHistory length disagrees with the full timeline truncated to its own minute`,
      );
    }
  }
});

// --- 6. every required replay point resolves safely -------------------------

test("every bundled fixture resolves the standard replay checkpoints safely and always ends in a Full time snapshot", async () => {
  const bundled = await loadBundledFixtures();
  for (const { fileName, fixture } of bundled) {
    assert.ok(fixture.snapshots.length > 0, `${fileName}: no snapshots at all`);
    assert.equal(fixture.snapshots[fixture.snapshots.length - 1].label, "Full time", `${fileName}: last snapshot must be Full time`);
    // Every configured checkpoint that genuinely appears must respect the match's own duration -- never inventing extra playing time.
    for (const snap of fixture.snapshots) {
      assert.ok(snap.minute <= fixture.finalMinute + MINUTE_EPSILON, `${fileName}: snapshot "${snap.label}" minute exceeds the match's own final minute`);
    }
  }
});

// --- 7. genuine model inference runs on every fixture ------------------------

test("genuine trained-model inference runs successfully on every snapshot of every bundled fixture, producing a valid probability", async () => {
  const bundled = await loadBundledFixtures();
  let evaluated = 0;
  for (const { fileName, fixture } of bundled) {
    for (const snap of fixture.snapshots) {
      const match = buildMatch(fixture, snap);
      const goalHistory: GoalHistoryPoint[] = snap.goalHistory;
      const liveFeatures = deriveLiveFeatures(match, goalHistory);
      assert.ok(liveFeatures.available, `${fileName}: snapshot "${snap.label}" -- live features unavailable: ${!liveFeatures.available ? liveFeatures.missingFields.join(", ") : ""}`);
      if (!liveFeatures.available) continue;
      const { output } = explainInference(NEXT_GOAL_NONE_MODEL, liveFeatures.input);
      assert.ok(
        output.model_probability_next_goal_none >= 0 && output.model_probability_next_goal_none <= 1,
        `${fileName}: snapshot "${snap.label}" -- probability out of range`,
      );
      assert.ok(
        Math.abs(output.model_probability_another_goal - (1 - output.model_probability_next_goal_none)) < 1e-9,
        `${fileName}: snapshot "${snap.label}" -- another-goal probability is not the exact complement`,
      );
      evaluated++;
    }
  }
  assert.ok(evaluated >= bundled.length * 5, `expected inference to run on many snapshots, only ran ${evaluated}`);
});

// --- 8. model probabilities are not stored in bundled JSON ------------------

test("bundled fixture JSON never stores a pre-computed model probability -- only raw match state, computed at request time", async () => {
  const bundled = await loadBundledFixtures();
  const forbiddenKeys = ["modelProbability", "model_probability_next_goal_none", "model_probability_another_goal", "fairProbability", "edgePp"];
  for (const { fileName, raw } of bundled) {
    const parsed = JSON.parse(raw);
    const seen = new Set<string>();
    const collectKeys = (value: unknown) => {
      if (Array.isArray(value)) {
        value.forEach(collectKeys);
      } else if (value && typeof value === "object") {
        for (const [k, v] of Object.entries(value)) {
          seen.add(k);
          collectKeys(v);
        }
      }
    };
    collectKeys(parsed);
    for (const forbidden of forbiddenKeys) {
      assert.ok(!seen.has(forbidden), `${fileName}: must not store a pre-computed "${forbidden}" field`);
    }
  }
});

// --- 13. no raw TxLINE payload, secret, or environment file is added --------

test("bundled fixture JSON never embeds a raw TxLINE payload shape or a credential-looking field", async () => {
  const bundled = await loadBundledFixtures();
  const suspiciousSubstrings = ["Participant1Id", "Participant2Id", "scores_historical", "odds_updates", "apiToken", "guestToken", "API_KEY", "SECRET"];
  for (const { fileName, raw } of bundled) {
    for (const needle of suspiciousSubstrings) {
      assert.ok(!raw.includes(needle), `${fileName}: must not contain "${needle}" (raw TxLINE payload shape or credential-looking field)`);
    }
  }
});

// --- 9/10/11/12. provider.ts's resolution order: real TxLINE preferred,
// bundled fallback only when zero real fixtures exist, never mixed, every
// bundled fixture exposed. Structural proof via source-scan (provider.ts
// carries `import "server-only"` and cannot be imported directly outside
// Next's bundler -- see this file's header comment); the corresponding
// live behavioural proof (moving ml/data/raw aside and hitting the real
// /api/historical/fixtures route) is the deployment-style verification
// step run separately against the dev server, not a unit test. -----------

test("lib/historical/provider.ts falls back to bundled fixtures only when zero real TxLINE fixtures exist, and never combines the two in one response", async () => {
  const source = await readSource("lib/historical/provider.ts");
  assert.ok(source.includes("if (summaries.length === 0)"), "must gate the bundled fallback on zero real TxLINE summaries");
  assert.ok(source.includes("await listBundledFixtures()"), "must read the bundled fixtures via bundledProvider.ts, never a second copy of that logic");
  // The two branches assign to the same `baseSummaries` variable -- structurally, only one of the two collections is ever used per response.
  assert.ok(/baseSummaries = bundled\s*[\s\S]*?\.sort/.test(source), "the bundled branch must fully replace, not append to, the real-fixture summaries");
  assert.ok(/baseSummaries = summaries\.sort/.test(source), "the real-fixture branch must be the summaries actually found on disk, not a mix");
});

test("lib/historical/provider.ts's getHistoricalFixtureDetail() tries the real TxLINE fixture first and only falls back to the bundled fixture with the same id", async () => {
  const source = await readSource("lib/historical/provider.ts");
  const loadedIdx = source.indexOf("const loaded = await loadFixture(fixtureId);");
  const bundledIdx = source.indexOf("return getBundledFixtureDetail(fixtureId);");
  assert.ok(loadedIdx !== -1 && bundledIdx !== -1 && loadedIdx < bundledIdx, "real TxLINE lookup must be attempted before the bundled fallback");
});

test("lib/historical/bundledProvider.ts reads fixtures from the static manifest, never a runtime directory scan", async () => {
  const source = await readSource("lib/historical/bundledProvider.ts");
  assert.ok(source.includes('from "./bundled/manifest.ts"'), "must read the generated static manifest");
  const codeOnly = source
    .split("\n")
    .filter((line) => !line.trim().startsWith("//"))
    .join("\n");
  assert.ok(!/readdir\(/.test(codeOnly), "must never call readdir() at runtime -- see scripts/generate-bundled-fixture-manifest.ts's own rationale");
});

test("the generated manifest lists every *.json file actually committed under lib/historical/bundled/, with no drift", async () => {
  const bundled = await loadBundledFixtures();
  const manifestSource = await readSource("lib/historical/bundled/manifest.ts");
  const importedFiles = [...manifestSource.matchAll(/from\s+"\.\/(.+?\.json)"/g)].map((m) => m[1]);
  const onDisk = bundled.map((b) => b.fileName).sort((a, b) => a.localeCompare(b));
  assert.deepEqual([...importedFiles].sort((a, b) => a.localeCompare(b)), onDisk, "manifest.ts must import exactly the *.json files present on disk");
});

// --- 14. Live mode remains unchanged ----------------------------------------

test("Live mode never imports the bundled-fixture manifest, provider, or generator tooling added for Historical Replay", async () => {
  for (const file of ["components/LiveView.tsx", "lib/txline/client.ts", "lib/txline/provider.ts", "lib/txline/publicSnapshot.ts"]) {
    const source = await readSource(file);
    assert.ok(!source.includes("bundled/manifest"), `${file} must never import the bundled-fixture manifest`);
    assert.ok(!source.includes("bundledProvider"), `${file} must never import lib/historical/bundledProvider.ts`);
    assert.ok(!source.includes("historical/provider"), `${file} must never import lib/historical/provider.ts`);
  }
});
