// AUTO-GENERATED by scripts/generate-bundled-fixture-manifest.ts -- do not hand-edit.
// Regenerate after adding/removing a fixture under lib/historical/bundled/:
//   npx tsx scripts/generate-bundled-fixture-manifest.ts
//
// Explicit static JSON imports (never a runtime fs.readdir() scan) so
// Next.js's build-time file tracing always includes every bundled fixture
// in the production/Vercel serverless bundle -- see
// lib/historical/bundledProvider.ts and this script's own module comment.

import type { BundledFixture } from "../bundledProvider.ts";
import fixture_statsbomb_2018_7534 from "./statsbomb_2018_7534.json" with { type: "json" };
import fixture_statsbomb_2018_7541 from "./statsbomb_2018_7541.json" with { type: "json" };
import fixture_statsbomb_2018_7554 from "./statsbomb_2018_7554.json" with { type: "json" };
import fixture_statsbomb_2018_7563 from "./statsbomb_2018_7563.json" with { type: "json" };
import fixture_statsbomb_2018_7576 from "./statsbomb_2018_7576.json" with { type: "json" };
import fixture_statsbomb_2018_7580 from "./statsbomb_2018_7580.json" with { type: "json" };
import fixture_statsbomb_2018_7585 from "./statsbomb_2018_7585.json" with { type: "json" };
import fixture_statsbomb_2018_8655 from "./statsbomb_2018_8655.json" with { type: "json" };
import fixture_statsbomb_2018_8658 from "./statsbomb_2018_8658.json" with { type: "json" };

export const BUNDLED_FIXTURES: BundledFixture[] = [
  fixture_statsbomb_2018_7534 as BundledFixture,
  fixture_statsbomb_2018_7541 as BundledFixture,
  fixture_statsbomb_2018_7554 as BundledFixture,
  fixture_statsbomb_2018_7563 as BundledFixture,
  fixture_statsbomb_2018_7576 as BundledFixture,
  fixture_statsbomb_2018_7580 as BundledFixture,
  fixture_statsbomb_2018_7585 as BundledFixture,
  fixture_statsbomb_2018_8655 as BundledFixture,
  fixture_statsbomb_2018_8658 as BundledFixture,
];
