import type { PaperTrade } from "./types";

// Small set of simulated historical trades so the dashboard reads as a live
// trading log from the first load, before the user records anything new.
export const SEED_TRADES: PaperTrade[] = [
  {
    id: "seed-1",
    timestamp: "2026-07-14T19:12:00.000Z",
    matchId: "por-ned",
    matchLabel: "Portugal vs Netherlands",
    marketId: "matchWinner",
    marketLabel: "Match Winner",
    selectionId: "home",
    selectionLabel: "Portugal",
    odds: 2.6,
    stake: 25,
    potentialReturn: 65,
    signal: "BUY",
    status: "won",
    pnl: 40,
  },
  {
    id: "seed-2",
    timestamp: "2026-07-14T20:47:00.000Z",
    matchId: "eng-fra",
    matchLabel: "England vs France",
    marketId: "overUnder",
    marketLabel: "Total Goals",
    selectionId: "over",
    selectionLabel: "Over 2.5",
    odds: 2.1,
    stake: 15,
    potentialReturn: 31.5,
    signal: "BUY",
    status: "lost",
    pnl: -15,
  },
  {
    id: "seed-3",
    timestamp: "2026-07-15T09:03:00.000Z",
    matchId: "bra-arg",
    matchLabel: "Brazil vs Argentina",
    marketId: "nextGoal",
    marketLabel: "Next Team to Score",
    selectionId: "home",
    selectionLabel: "Brazil",
    odds: 2.1,
    stake: 20,
    potentialReturn: 42,
    signal: "BUY",
    status: "open",
    pnl: null,
  },
];
