/**
 * Regenerates lib/historical/bundled/manifest.ts -- an explicit, statically-
 * importable list of every committed bundled fixture JSON file.
 *
 * Run with:
 *   npx tsx scripts/generate-bundled-fixture-manifest.ts
 *
 * WHY THIS EXISTS: lib/historical/bundledProvider.ts used to discover
 * fixtures with a runtime fs.readdir() over lib/historical/bundled/. That
 * works locally, but Next.js's production build traces file dependencies
 * statically (which files a route's compiled output actually needs) to
 * decide what ships in the Vercel serverless bundle -- a directory scanned
 * only at request time via readdir() is invisible to that trace, so newly
 * added JSON fixtures risk silently vanishing in production even though
 * `npm run build` succeeds and everything works with `next dev` locally.
 *
 * The fix is this generated manifest: one explicit
 * `import fixture from "./x.json" with { type: "json" }` per committed
 * fixture (the exact same import-attribute JSON-import form already proven
 * safe for Next's bundler by lib/model/nextGoalNoneModel.ts's trained-model
 * JSON import). A literal static import is always part of the module graph
 * Next traces, so every listed fixture is guaranteed to ship.
 *
 * Run this script again any time a fixture JSON file is added to or removed
 * from lib/historical/bundled/ (ml/build_bundled_replay_fixture.py's own
 * docstring points here). This script only ever reads *.json file NAMES in
 * that directory to generate import statements -- it never inspects or
 * alters fixture contents, never fabricates a fixture, and the generated
 * file is committed like any other source file (not built at deploy time).
 */

import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const BUNDLED_DIR = path.join(process.cwd(), "lib", "historical", "bundled");
const MANIFEST_PATH = path.join(BUNDLED_DIR, "manifest.ts");

function identifierFor(fileName: string): string {
  const stem = fileName.replace(/\.json$/, "");
  return `fixture_${stem.replace(/[^a-zA-Z0-9_]/g, "_")}`;
}

async function main() {
  const fileNames = (await readdir(BUNDLED_DIR))
    .filter((f) => f.endsWith(".json"))
    .sort((a, b) => a.localeCompare(b));

  if (fileNames.length === 0) {
    throw new Error(`No *.json fixtures found in ${BUNDLED_DIR} -- refusing to write an empty manifest.`);
  }

  const importLines = fileNames
    .map((f) => `import ${identifierFor(f)} from "./${f}" with { type: "json" };`)
    .join("\n");
  const arrayEntries = fileNames.map((f) => `  ${identifierFor(f)} as BundledFixture,`).join("\n");

  const contents = `// AUTO-GENERATED by scripts/generate-bundled-fixture-manifest.ts -- do not hand-edit.
// Regenerate after adding/removing a fixture under lib/historical/bundled/:
//   npx tsx scripts/generate-bundled-fixture-manifest.ts
//
// Explicit static JSON imports (never a runtime fs.readdir() scan) so
// Next.js's build-time file tracing always includes every bundled fixture
// in the production/Vercel serverless bundle -- see
// lib/historical/bundledProvider.ts and this script's own module comment.

import type { BundledFixture } from "../bundledProvider.ts";
${importLines}

export const BUNDLED_FIXTURES: BundledFixture[] = [
${arrayEntries}
];
`;

  await writeFile(MANIFEST_PATH, contents, "utf-8");
  console.log(`Wrote ${MANIFEST_PATH} with ${fileNames.length} bundled fixture(s):`);
  for (const f of fileNames) console.log(`  - ${f}`);
}

main();
